### ISSUE TITLE
Intro courses to be completed

### ISSUE THREAD

**Issue by dillydallier** [dillydallier/epicodus-intro#1]
## TODO

*Tasks left to complete the intro course*
🎉 🙆 🎊 
cc @verazu

* [ ] How to make a website (8 h)
* [ ] CSS basics (7 h)
* [ ] JaveScript basics (6 h)
* [ ] CSS layout basics (2 h)
* [ ] Responsive layouts (47 m)
* [ ] CSS Flexbox layout (105 m)
* [ ] HTML forms (2 h)
* [ ] JavaScript Loops, Arrays and Objects (4 h)
* [ ] CSS selectors (2 h)
* [ ] jQuery basics (5 h)
* [ ] Bootstrap 4 basics (2 h)
* [ ] HTML tables (59 m)
* [ ] Interactive web pages with JavaScript (2 h)
* [ ] HTML video and audio (116 m)
* [ ] AJAX basics (5 h)
* [ ] Object-oriented JavaScript (2 h)
* [ ] Accessibility (101 m)
* [ ] Website optimization (89 m)
* [ ] Console foundations (3 h)
* [ ] Git basics (4 h)
* [ ] Front end performance optimization (92 m)
